name: projectx
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  url_launcher: ^6.0.13
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  android_intent_plus: ^5.3.0
  stroke_text: ^1.0.0
  faker: ^2.1.0
  helpers: ^1.2.3
  random_date: ^0.0.7
  get: ^4.6.6
  pinput: ^5.0.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  flutter_floating_bottom_bar: ^1.2.0
  google_sign_in: ^6.2.1
  permission_handler: ^11.2.0
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  liquid_pull_to_refresh: ^3.0.1
  hidden_drawer_menu: ^3.0.1
  carousel_slider: ^5.0.0
  chat_gpt_sdk: ^3.1.4
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  lazy_load_scrollview: ^1.3.0
  flutter_webrtc: ^0.13.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  firebase_storage: ^12.4.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  file_picker: ^9.2.1
  chewie: ^1.7.4
  photo_view: ^0.15.0
  flutter_advanced_drawer: ^1.3.5
  hidden_drawer: ^0.0.1
  flutter_native_splash: ^2.3.10
  flutter_carousel_slider: ^1.1.0
  extended_text_field: ^16.0.2
  qr_code_scanner: ^1.0.1
  socket_io_client: ^3.0.2
  intl: any
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  flutter_callkit_incoming: ^2.0.1+2
  background_fetch: ^1.3.8
  vibration: ^3.1.3
  giphy_picker: ^3.0.2
  local_auth: ^2.2.0
  speech_to_text: ^7.0.0
  path: ^1.9.0
  syncfusion_flutter_pdfviewer:
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_datepicker: ^29.1.33

  syncfusion_flutter_core: any
  wakelock_plus: ^1.2.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/chat.png
    - assets/chat2.png
    - assets/chat3.png
    - assets/imageup.png
    - assets/videoup.png
    - assets/audioup.png
    - assets/docup.png
    - assets/profile.png
    - assets/editprofile.png
    - assets/messageup.png
